# MINUET AUTO MODE PRESET TEMPLATE PACKAGE FOR THE THERMOSTAT

number:
  - id: minuet_auto_preset_${minuet_auto_preset_id}_thermostat_fan_speed
    name: "Auto preset ${minuet_auto_preset_name} thermostat fan speed"
    icon: mdi:thermostat-cog
    platform: template
    entity_category: config
    min_value: 1
    max_value: 10
    step: 1
    initial_value: ${minuet_auto_preset_thermostat_fan_speed}
    mode: box
    optimistic: true
    restore_value: true
  - id: minuet_auto_preset_${minuet_auto_preset_id}_thermostat_target_temperature
    name: "Auto preset ${minuet_auto_preset_name} thermostat target"
    icon: mdi:thermometer-cog
    entity_category: config
    device_class: temperature
    unit_of_measurement: °C
    mode: box
    platform: template
    optimistic: true
    min_value: ${minuet_auto_thermostat_min_target_temperature}
    max_value: ${minuet_auto_thermostat_max_target_temperature}
    step: ${minuet_auto_thermostat_step_target_temperature}
    initial_value: ${minuet_auto_preset_thermostat_target_temperature}
    restore_value: true
select:
  - id: minuet_auto_preset_${minuet_auto_preset_id}_thermostat_fan_mode
    platform: template
    name: "Auto preset ${minuet_auto_preset_name} thermostat fan mode"
    icon: mdi:thermostat-cog
    entity_category: config
    optimistic: true
    options:
      - "Auto"
      - "On"
      - "Off"
    initial_option: ${minuet_auto_preset_thermostat_fan_mode}
    restore_value: true
switch:
  - id: minuet_auto_preset_${minuet_auto_preset_id}_thermostat_on
    platform: template
    name: "Auto preset ${minuet_auto_preset_name} thermostat on"
    icon: mdi:thermostat-cog
    entity_category: config
    optimistic: true
    restore_mode: ${"RESTORE_DEFAULT_ON" if minuet_auto_preset_thermostat_on else "RESTORE_DEFAULT_OFF"}
