# MINUET AUTO MODE PRESET TEMPLATE PACKAGE FOR THE AQI MONITOR

switch:
  - id: minuet_auto_preset_${minuet_auto_preset_id}_aqi_monitor_on
    platform: template
    name: "Auto preset ${minuet_auto_preset_name} AQI monitor on"
    icon: mdi:thermostat-cog
    entity_category: config
    optimistic: true
    restore_mode: ${"RESTORE_DEFAULT_ON" if minuet_auto_preset_aqi_monitor_on else "RESTORE_DEFAULT_OFF"}
