# MINUET ENVIRONMENT ACCESSORY PACKAGE
#
# Reads sensors from the environmental sensor accessory.
# Refer to the environment accessory documentation for details.

defaults:
  # The environment sensor I2C address jumper setting on the circuit board
  # Valid values: `low` (silkscreen label `ADDR -`) or `high` (silkscreen label `ADDR +`).
  minuet_environment_jumper_address: low
  # The BMP580 I2C address.
  minuet_environment_bmp580_i2c_addresses:
    low: 0x46
    high: 0x47
  minuet_environment_bmp580_i2c_address: ${minuet_environment_bmp580_i2c_addresses[minuet_environment_jumper_address]}
  # The STCC4 I2C address.
  minuet_environment_stcc4_i2c_addresses:
    low: 0x64
    high: 0x65
  minuet_environment_stcc4_i2c_address: ${minuet_environment_stcc4_i2c_addresses[minuet_environment_jumper_address]}

substitutions:
  # Offer sensors for automatic control.
  minuet_auto_sensors:
    temperature:
      - name: BMP580
        sensor_id: minuet_environment_temperature_bmp580
        priority: 500
      - name: SHT40
        sensor_id: minuet_environment_temperature_sht40
        priority: 500
    humidity:
      - name: SHT40
        sensor_id: minuet_environment_humidity_sht40
        priority: 500
    co2:
      - name: STCC4
        sensor_id: minuet_environment_co2_stcc4
        priority: 500
  # Disable components when accessory is not installed.
  minuet_package_accessory_environment_setup_condition:
    sensor:
      - id: !extend minuet_environment_bmp580
        setup_condition: !lambda 'return minuet::accessory::is_installed("environment");'

external_components:
  - source: github://j9brown/esphome@stcc4-pr
    components: [stcc4]
    refresh: always

esphome:
  on_boot:
    - priority: ${minuet_accessory_setup_priority}
      then:
        - lambda: |-
            // Detect BMP580 by reading its chip id register
            uint8_t write_buf[1] = { 0x01 };
            uint8_t read_buf[1] = { 0x00 };
            if (id(minuet_i2c).write_readv(${minuet_environment_bmp580_i2c_address},
                write_buf, sizeof(write_buf), read_buf, sizeof(read_buf)) != esphome::i2c::NO_ERROR ||
                read_buf[0] != 0x50) {
              return; // accessory not detected
            }
            // TODO: Detect STCC4

            minuet::accessory::install({
              .id = "environment",
            });

sensor:
  - id: minuet_environment_bmp580
    platform: bmp581_i2c
    i2c_id: minuet_i2c
    address: ${minuet_environment_bmp580_i2c_address}
    temperature:
      id: minuet_environment_temperature_bmp580
      name: "Temperature from BMP580"
      oversampling: "none"
      iir_filter: "off"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 5
            send_first_at: 5
        - delta: 0.05
        - round_to_multiple_of: 0.1
    pressure:
      id: minuet_environment_pressure_bmp580
      name: "Pressure from BMP580"
      oversampling: "4x"
      iir_filter: "off"
      accuracy_decimals: 1
      unit_of_measurement: "hPa"
      filters:
        - multiply: 0.01  # convert from Pa to hPa
        - sliding_window_moving_average:
            window_size: 30
            send_every: 10
            send_first_at: 10
        - delta: 0.5
        - round_to_multiple_of: 0.1
    update_interval: 1s
  - id: minuet_environment_stcc4
    platform: stcc4
    i2c_id: minuet_i2c
    address: ${minuet_environment_stcc4_i2c_address}
    measurement_mode: continuous
    ambient_pressure_compensation_source: minuet_environment_pressure_bmp580
    co2:
      id: minuet_environment_co2_stcc4
      name: "CO₂ from STCC4"
      accuracy_decimals: 0
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 5
            send_first_at: 5
        - delta: 0.5
        - round_to_multiple_of: 1
    temperature:
      id: minuet_environment_temperature_sht40
      name: "Temperature from SHT40"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 5
            send_first_at: 5
        - delta: 0.05
        - round_to_multiple_of: 0.1
    humidity:
      id: minuet_environment_humidity_sht40
      name: "Humidity from SHT40"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 5
            send_first_at: 5
        - delta: 0.05
        - round_to_multiple_of: 0.1
    update_interval: 1.2s

packages:
  - ${minuet_package_accessory_environment_setup_condition if minuet_esphome_has_setup_condition else {}}
