# MINUET BATTERY MONITOR PACKAGE
#
# Reads the supply voltage and compares it to configurable voltage thresholds.
# Implements the battery safety lock.

substitutions:
  # The battery voltage hysteresis determines the change in observed battery voltage needed to disengage the
  # battery safety lock after a battery voltage too high or too low condition occurs.
  minuet_battery_voltage_hysteresis: 0.4

sensor:
  - id: minuet_battery_voltage
    name: "Battery voltage"
    icon: mdi:car-battery
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    unit_of_measurement: V
    accuracy_decimals: 1
    platform: adc
    pin:
      number: 5
      ignore_strapping_warning: true
    attenuation: 12db
    samples: 4
    sampling_mode: avg
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 5
          send_first_at: 5
      - multiply: 11
      - delta: 0.05
      - round_to_multiple_of: 0.1
    update_interval: 0.5s
    on_value:
      then:
        - script.execute: minuet_battery_update

number:
  - id: minuet_battery_voltage_low
    name: "Battery voltage low limit"
    icon: mdi:battery-alert
    entity_category: config
    device_class: voltage
    unit_of_measurement: V
    mode: box
    platform: template
    optimistic: true
    min_value: 9
    max_value: 16
    step: 0.1
    restore_value: true
    initial_value: 10.8
    on_value:
      then:
        - script.execute: minuet_battery_update
  - id: minuet_battery_voltage_high
    name: "Battery voltage high limit"
    icon: mdi:battery-alert
    entity_category: config
    device_class: voltage
    unit_of_measurement: V
    mode: box
    platform: template
    optimistic: true
    min_value: 9
    max_value: 16
    step: 0.1
    restore_value: true
    initial_value: 15.2
    on_value:
      then:
        - script.execute: minuet_battery_update

script:
  - id: minuet_battery_update
    mode: single
    then:
      - lambda: |-
            auto& lock = id(minuet_battery_safety_lock);
            const float voltage = id(minuet_battery_voltage).state;
            const float low = id(minuet_battery_voltage_low).state;
            const float high = id(minuet_battery_voltage_high).state;
            if (high <= low) {
              lock->publish_state(true); // degenerate state, settings are malformed
            } else if (!lock->state) {
              lock->publish_state(voltage < low || voltage > high);
            } else {
              const float hysteresis = std::min(${minuet_battery_voltage_hysteresis}f, (high - low) / 3);
              lock->publish_state(voltage < low + hysteresis || voltage > high - hysteresis);
            }
