# MINUET RADIO PACKAGE FOR BLUETOOTH
#
# TODO: Implement secure bonds for remote control, see https://github.com/esphome/esphome/pull/17562

defaults:
  # The state of the radio on power up and after a factory reset.
  # Use one of the following values:
  #   - `RESTORE_DEFAULT_OFF`: Restore the radio switch state from persistent storage
  #                            and set it to OFF by default after a factory reset.
  #   - `RESTORE_DEFAULT_ON`:  Restore the radio switch state from persistent storage
  #                            and set it to ON by default after a factory reset.
  #   - `ALWAYS_OFF`:          Set the radio switch state to OFF on power up.
  #   - `ALWAYS_ON`:           Set the radio switch state to ON on power up.
  minuet_radio_bluetooth_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  build_flags:
    - "-DMINUET_RADIO_BLUETOOTH"

switch:
  - id: minuet_radio_bluetooth
    name: "Bluetooth radio"
    icon: mdi:bluetooth
    platform: template
    optimistic: true
    restore_mode: ${minuet_radio_bluetooth_restore_mode}
    entity_category: config
    disabled_by_default: ${minuet_use_disabled_by_default}
    setup_priority: 340  # Between BLUETOOTH and AFTER_BLUETOOTH
    on_turn_on:
      then:
        - logger.log:
            format: "Bluetooth LE radio enabled"
            level: INFO
        - ble.enable:
    on_turn_off:
      then:
        - logger.log:
            format: "Bluetooth LE radio disabled"
            level: INFO
        - ble.disable:
        - switch.turn_off: minuet_radio_pairing_mode

esp32_ble:
  id: minuet_ble
  enable_on_boot: false
  max_connections: 5
