# MINUET TEMPLATE CONFIGURATION WITH LOCAL MINUET PACKAGES
#
# Overrides the template configuration to use local packages.

substitutions:
  minuet_origin: local

packages:
  - !include minuet_template.yaml
